### ISSUE TITLE
Narrowing -- synchronise the narrowed text or the widened text?

### ISSUE THREAD

**Issue by phil-s** [KarimAziev/chrome-emacs#10]
At the moment, narrowing the Emacs buffer immediately removes all of the hidden text from the browser textarea, and a user can submit without realising they've 'deleted' most of what they were writing.

(I've done this when narrowing to a code block to change major modes to the programming mode.)

One could argue this either way, but I think it would be helpful (less likely to cause data loss) if the synchronisation was with the widened buffer content by default.

**Comment by KarimAziev** [comment]
That makes sense, thanks for bringing it up! I pushed this to the branch [feat/widen](https://github.com/KarimAziev/atomic-chrome/tree/feat/widen) on the atomic chrome. Please try it, and then we can merge it to the main.

**Comment by phil-s** [comment]
Thank you @KarimAziev; I've tested that change, and it looks good to me.

**Comment by KarimAziev** [comment]
Great to hear! I've merged the change into the main branch, and I'm closing the issue now. Feel free to reopen if anything else comes up.

**Comment by phil-s** [comment]
Thank you for the quick fix -- and to everyone involved for this excellent project (and for making it work on Firefox).

Cheers!
