### ISSUE TITLE
Idea/Hope: per-site startup hooks.

### ISSUE THREAD

**Issue by stephenwithav** [KarimAziev/chrome-emacs#4]
The goal: if I'm doing a coding interview on HackerRank.com, I'd like emacs to run `go-playground`, replace the buffer's contents, and sync the buffer with HackerRank's text editor.

As is, any loaded Go buffers are loaded without a go.mod, making it poor for Go devs.

**Comment by KarimAziev** [comment]
Thanks for the suggestion!

As far as I understand, you want to run custom actions like `go-playground`, replace buffer contents, etc., for specific sites like HackerRank. You can do this by combining `atomic-chrome-create-file-strategy` with hooks in `atomic-chrome-edit-mode-hook`.

Here's how you can get started:

1. Set up the custom variable `atomic-chrome-create-file-strategy`. Use this to specify where files should be created based on the URL and file extension. Place a `go.mod` file in this directory to ensure your Go buffers have the proper setup.

```elisp
;; Add a new rule for creating the file strategy.
(add-to-list 'atomic-chrome-create-file-strategy
             '("~/hackerrank/go/" ;; The edit file should be created in this directory.
               :url ;; If the hostname of the URL is one of:
               ("www.hackerrank.com")
               ;; AND the file extension is one of:
               :extension
               ("go")))
```

2. Add a custom hook to `atomic-chrome-edit-mode-hook` to perform your specific setup when a buffer is created:

```elisp
(defun my-hackerrank-go-setup ()
  (when (and buffer-file-name
             (string-prefix-p "~/hackerrank/go/" buffer-file-name)
             (equal (file-name-extension buffer-file-name) "go"))
    ;; Delete initial buffer content if needed
    ;; (delete-region (point-min) (point-max))
    (insert "Hello, world")
    ;; Run go-playground or any other setup you need
    (go-playground-run-setup)
  ))

(add-hook 'atomic-chrome-edit-mode-hook 'my-hackerrank-go-setup)
```

This way, Go files from HackerRank will be created in `~/hackerrank/go/`, and you can run your setup code when those buffers are opened.

Note, the real file, not just the buffer, will be created in the `~/hackerrank/go/` directory, and you may also want to configure the custom variable `atomic-chrome-auto-remove-file`.

Hope this helps! Let me know if you need any more info.

**Comment by stephenwithav** [comment]
Thanks, @KarimAziev!  This worked perfectly.  Now I can do coding assessments with confidence.
