### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by Thaodan** [KarimAziev/chrome-emacs#5]
Hey is there any chance you could support Firefox?

**Comment by KarimAziev** [comment]
Thanks for your interest!

Actually, I have had a version ready for Firefox for a while. My main challenge was to find a graceful way to manage the build workflow for both Firefox and Chrome.

But your suggestion is valuable and motivates me to think about this again. Stay tuned for updates!

**Comment by KarimAziev** [comment]
Hey @Thaodan,

The Firefox version is now supported. Check it out at: [Chrome Emacs on Firefox](https://addons.mozilla.org/addon/chrome-emacs/).

I will close this issue, but feel free to open a new one if you encounter any problems.

**Comment by Thaodan** [comment]
Thanks I will try.
I hope your extension will deal better with pages having long input
buffers such as Github compared to Ghosttext.

**Comment by KarimAziev** [comment]
If you mean the bug with incomplete frames in websockets (see [issue](https://github.com/alpha22jp/atomic-chrome/issues/77)), make sure that you use the [atomic-chrome fork](https://github.com/KarimAziev/atomic-chrome), because it is fixed in the fork.

**Comment by KarimAziev** [comment]
Yes, this works, but ensure that you use version 0.5.2, not 0.5.1.
